### ISSUE TITLE
Bug about head drops

### ISSUE THREAD

**Issue by kaimokene** [Thatsmusic99/HeadsPlus#12]
Hello i was killing blazes and it threw this in the console and i wasnt getting any heads from the blazes earlier today i did get a sheep head. So i dont know whats different or maybe it works with other mobs
https://pastebin.com/vJeirZVD

Paper 373
Headsplus 5.17

**Comment by Thatsmusic99** [comment]
Can you send me your heads.yml please? This has been fixed but I also want to double check something.

**Comment by kaimokene** [comment]
Sure. https://pastebin.com/htZbaY68

**Comment by Thatsmusic99** [comment]
Alright I'm off my laptop now but will look into this tomorrow. Cheers.

**Comment by Thatsmusic99** [comment]
Fixed in latest version. (5.1.8)
