### ISSUE TITLE
Husk head isnt a Husk

### ISSUE THREAD

**Issue by kaimokene** [Thatsmusic99/HeadsPlus#13]
Hello. I am back again :D Husk head seems to appear like some blue skin with white eyes and headphones. Probably whoevers head ur using has changed their skin.
Using Paper 380 and headsplus 5.18

**Comment by Thatsmusic99** [comment]
https://www.spigotmc.org/threads/headsplus-1-8-x-1-13-x-halloween-update.237088/page-12

This was a funny one... I didn't even realise it at first.
