### ISSUE TITLE
java.lang.NullPointerException[BUG]

### ISSUE THREAD

**Issue by Markiie** [Thatsmusic99/HeadsPlus#13]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
State here when you have checked the following points above.

### Description of the bug
Plugin didnt work at all and has been disabled in console. The console is saying the following:  https://pastebin.com/U5SPUmPc 

The follwoing was the bug report made in the plugins folder on HeadsPlus: https://pastebin.com/QDirpV9e

### To Reproduce
1. Downloaded plugin
2. Added plugin to server
3. Error appeared 

### Screenshots
Links provided above ^

### Has a debug report been generated? YES
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

### Required information
- Server version: Paper 1.14
- HeadsPlus version: 6.6.1
- Whether or not the plugin uses MySQL: No
- Server type (e.g Spigot, Paper):  Paper Build 186
- Uses Vault: Yes
- Any other pieces of information that may be required.

## Additional information
Add any other information/notes you'd like to add at the bottom

**Comment by Thatsmusic99** [comment]
Please try the snapshot here, which was meant to be checked for in the first place: https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v6.6.2-SNAPSHOT-1

**Comment by wsngamerz** [comment]
I have this same issue however I can get HeadsPlus to load correctly by disabling levels in the config file.

Server Log: https://pastebin.com/AtiFXrAS
HeadsPlus Error Report: https://pastebin.com/KEHMVMBq

**Comment by Thatsmusic99** [comment]
Thank you for the confirmation - I did just get the chance to run it (I started school this week so I'm trying to catch up on plugin developing again, but will have to change the weekly HeadsPlus updates to once a fortnight so I can concentrate on that and other projects), I'm looking into a fix now.

**Comment by Thatsmusic99** [comment]
Please let me know if the issue still consists^
