### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AlexandruSAN2** [Thatsmusic99/HeadsPlus#15]
[
  {
    "Special message": "NullPointer for president!",
    "Locale": "Romanian, Romania",
    "MySQL is enabled": false,
    "Exception details": {
      "Stacktrace": [
        "java.lang.NullPointerException\n\tat io.github.thatsmusic99.headsplus.config.levels.HeadsPlusLevels.loadLevels(HeadsPlusLevels.java:47)\n\tat io.github.thatsmusic99.headsplus.config.levels.HeadsPlusLevels.reloadC(HeadsPlusLevels.java:40)\n\tat io.github.thatsmusic99.headsplus.config.ConfigSettings.enable(ConfigSettings.java:17)\n\tat io.github.thatsmusic99.headsplus.config.levels.HeadsPlusLevels.<init>(HeadsPlusLevels.java:25)\n\tat io.github.thatsmusic99.headsplus.HeadsPlus.createInstances(HeadsPlus.java:452)\n\tat io.github.thatsmusic99.headsplus.HeadsPlus.onEnable(HeadsPlus.java:108)\n\tat org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)\n\tat org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)\n\tat org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)\n\tat org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)\n\tat org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)\n\tat net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)\n\tat net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)\n\tat net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)\n\tat net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)\n\tat net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)\n\tat java.lang.Thread.run(Thread.java:748)\n"
      ],
      "Fired when": "Startup"
    },
    "Server version": "git-Paper-1618 (MC: 1.12.2)",
    "HeadsPlus version": "6.6.6",
    "Plugin values": {
      "MySQL is enabled": false,
      "Masks enabled": true,
      "Uses leaderboards": true,
      "Levels enabled": true,
      "Allows looting enchantment": true,
      "Uses heads selector": true,
      "Cached players": 0,
      "Total levels": 0,
      "Stops placement of sellable heads": false,
      "Droppable heads enabled": true,
      "Player death messages": false,
      "Total challenges": 931
    },
    "NMS version": "v1_12_R1",
    "Date": "11/02/2019 03:38:34",
    "Has Vault hooked": true
  }
]

**Comment by Thatsmusic99** [comment]
Whilst I did give a temporary workaround, will look into this for v7.0.0-PHASE-1.
