### ISSUE TITLE
About you 

### ISSUE THREAD

**Issue by Misio12320** [Thatsmusic99/HeadsPlus#15]
? can you please tell me why did you done that? Whats a harassmatic to me and racism... Wow and I was really thinking if I can trust you... I was thinking if you will not share my messages but what ever what I see now... I wanted to give you some time to let you give me the last chance... may now too :disappointed: what you done me now... You dont know me and you just nah... after looking at that all I dont have comment really.. you could depends on me... Youre now clear cause you got help and me not enjoy... I saw if you wanted attack me by your friends and you too by stalk right? We cannot repair that right? I helped you cause youre now not angry on suicide's and all so you can help me now too or what ever share that to your community... I did not attacked you by gender, racism to people with like you this tomboy and etc did not stalked you and want forgive but when you have own friends etc I will not attack you as you want... let me stay hurted for my last days ? You could tell me if you doesnt like hear some bullshits what I said you... Can we play something together ? I'm apologies :cry: .. Really dont know for what now if you stalked me more with tell all to your community.. @how about no... And you will never forgive me that right :broken_heart:  ?  ''In other words I'm so dense I didn't realise you can leave conversations... but nah I won't, not yet.'' what mean that ''not yet'' wanted to let me hurt more? I very like you and don't wanted to lose you cause we were only 3 days friends? Why you took that all real?? Can you please don't tell that to your community please can you think about that all alone? Can you exacly forgive me that youre better now and you told me to don't get hurted by you and dont get scared... Now im fucking scared everything fucking depression :fearful:  Hmmmm don't have ideas cuz you hurted my feels... Please really don't share that to your community however I can trust you... :tired_face: :cold_sweat:You gave me a lot of lucky feels and now pshh.. as I said you have own community friends and Im useless for you:sleepy: I was thinking if you give me on discord a rank some like a ''friends'' something I needed that and I got really bad things like you crabs me pshhhh... If you would have some small amount of feel others you shouldn't do that but I see something wrong here... Please change your status to bad human or some like this cause what the fuck ever you will show that to your community so whats the sense... Why you cannot forgive me that??? :( Im bored about that all and want to search in you trust.... Can you add me on my main account and give me a ''hug'' which will help me a lot please :(? or please I want be your friend whats the problem? Nah... You don't know how im hurted now if you would have some life you would help me a lot but no :(... I doesn't wanted to hurt you on this spigot just wanted get my answer. I dont have ideas how to repair that, its done I think. oh youre back pls dont hurt me I want only last chance from you Im really scared you now my heart I hear it from head to foots thats scaryyy. really forgive me that and belive if Im not a bad guy... :( I cannot life without you now cuz youre or you was my best friend ;( give me the last chance :( really I will change my self I will ask you how are you feels now and all... Just as I said dont share that to your community don't want get shamed :'( I can do everything to you for these friends... add my main account please... You see how are you now feel- good better and nah... Please unblock  :( I doesn't wanted to hurt you with that all as I said I just want be your friend cuz youre great... honely? Now look at your self (dont want critic you) but you really done bad to me... I think if human shouldnt do this. Please add :'( 
appreciate it at all... Just wanted tell you that on discord but you doesnt give me win to so... Really why you doing this? Youre better and got lesson and now ??? Why you dont give me the last chance Im now killed by you... I can call you a murder cause you broken me now . it's impossible to think what you did to me @Thatsmusic99 ... Do I need to give you time think about this or thats the end of that ''friends'' and my life or something you think? Im not scared hangman so if you want I can do this special for you <3 :+1: . Tbh I don't have feels to my life and others, thank you for that and youre not? or may enough to help me... Just remind your self if youre a murder killing a innocent boy like me... 
I can not be too honest cause you will know everything about me :). Generally may I felt to you something like a bigger friend and all. I said you if I wanted give you rest of my life to you, to get some help

**Comment by Misio12320** [comment]
Pshhh... Change your mind and come back... Or what the shit ever... By that all what I said you, youre now a bad person I mean sending my pm to you and blocking everywhere pshh... :sob:

**Comment by Thatsmusic99** [comment]
1. Completely unrelated to HeadsPlus.
2. I asked you to stop contacting me.
3. You went ahead and downrated my plugins out of scorn.

Now please stop trying to reach out to me.

**Comment by Misio12320** [comment]
Tbh and I wanted meet you in real life.. You dont see something wrong here? A random your user which want really get to know you and you doesnt give him this contact? Thats weird. Thanks for all. Good luck returning into normal life... For me its too late :( doesnt appreciate that all.. How can a people like you exisist on this world thats insaine. Waiting in hope to get friendly with you again :c

**Comment by Misio12320** [comment]
Pshhhh... Insaine insaine

**Comment by Thatsmusic99** [comment]
Actually it’s completely normal for me to not give my contact details to anyone. You don’t even know who I am. I have asked you to stop, stop now.

**Comment by Thatsmusic99** [comment]
Blocked
