### ISSUE TITLE
Balance is very long in stats display

### ISSUE THREAD

**Issue by oranges13** [Thatsmusic99/HeadsPlus#17]
### Short summary of issue
Balance in stats display has a lot of significant digits

### Server version
Spigot 1.13.2

### HeadsPlus version
5.2.7

### Detailed description (how you found it, what you were doing at the time)
The balance listed in the stats overview has many significant digits.
https://i.imgur.com/ORL82jB.png

### Expected behaviour
Balance is a reasonable length (2 significant digits?)

### Actual behaviour
All the significant digits are displayed

### Steps to reproduce
We are using Essentials Economy, which appears to store the balance with a lot of extra significant digits
Install headsplus
`/heads` command and hover over the stats icon at the top

### Any last notes?
n/a

**Comment by Thatsmusic99** [comment]
I forgot how annoying Essentials is with stupidly long and almost pointless decimal numbers. I'm not quite sure if this is an issue that directly points at HeadsPlus, the best I can really do is create a small workaround but may not work.

**Comment by oranges13** [comment]
Let me know, I am happy to submit an issue for them if that's more appropriate!

**Comment by Thatsmusic99** [comment]
Will be fixed in update 5.2.8 which will be on Spigot.
