### ISSUE TITLE
Sell GUI bug

### ISSUE THREAD

**Issue by Hardko** [Thatsmusic99/HeadsPlus#18]
### Short summary of issue
Hi. I have a problem when I sell a head, not only sells the heads, but also makes items disappear from the inventory.
### Server version
1.13.2
### HeadsPlus version
5.2.9
### Detailed description (how you found it, what you were doing at the time)
Players of my server notificated me about the bug, when they sells heads, part of the inventory disappear with the head. I use the sell GUI.
### Expected behaviour
Don't desapair items from inventory.
### Actual behaviour
Sometimes when sell heads, items desapair.
### Steps to reproduce
Try sell heads with items in the inventory, maybe like diamond pickaxe, diamond, iron, cobblestone, beef, etc.
### Any last notes?
First, sorry for my bad english, second, i thinked is a bug with /sell from essentialsX, but i delete the items to sell and the bug it happened again.

**Comment by Thatsmusic99** [comment]
I believe this has happened before but I’ll have to try and reproduce it. No promises that I will manage to, since I don’t think I’ve heard of the such.

**Comment by Thatsmusic99** [comment]
Currently unable to reproduce on Spigot 1.13.2.

Are you able to give me your server's IP so I can see this? Or perhaps a video of it happening? If possible of course.

**Comment by Hardko** [comment]
Of course, you need a special permission or something? I have disable the sell option, but if you need i can enable again. And I try to capture the bug in a video, but now I have a lot to do...
**Ip**: 185.243.152.140

**Comment by Hardko** [comment]
I have a video with the bug:
https://www.youtube.com/watch?v=Phq-YRkrg5s

Also I do a test with other problem I have in the server, and the items that disappear have NBT Tag, I don't know why, but these only items disappear.
In the video I put 2 stacks of iron ingots, one don't have NBT Tag and the other yes.

**Comment by Thatsmusic99** [comment]
NOW that makes much more sense. Will look into this.

**Comment by Thatsmusic99** [comment]
I did have a fix set up yesterday but currently I’ve got around 20 different things happening in my life and next week is not going to be much better either. I’ll test the patch I applied when I’m back later and will release it as a new plugin version.

**Comment by Thatsmusic99** [comment]
Fixed here. https://www.spigotmc.org/resources/headsplus-1-8-x-1-13-x.40265/update?update=256932
