### ISSUE TITLE
Issue trying to run with command_block.

### ISSUE THREAD

**Issue by dannegm** [Thatsmusic99/HeadsPlus#20]
This line may cause an issue when I trying to run the command through the command_block.

https://github.com/Thatsmusic99/HeadsPlus/blob/7f77512fe602e44f0fcc68973f01889c8d86f35d/main/java/io/github/thatsmusic99/headsplus/commands/MyHead.java#L32

**Comment by dannegm** [comment]
Sure, I've tried. I got the following message:
```
That player is offline
```

**Comment by Thatsmusic99** [comment]
Reproduced and will look into.

**Comment by Thatsmusic99** [comment]
Sadly I haven't had many results with this as the target selectors (@/p, @/e, etc) aren't being replaced with the player names and such. I'm trying out one last method and will see if that works.

**Comment by Thatsmusic99** [comment]
Can't seem to find any possible solution currently. Is this definitely needed for sure?

**Comment by steve4744** [comment]
Commandblocks in 1.13 can only target players (@p, etc.) for built-in commands, but not for plugin commands. There is an issue on Jira (https://hub.spigotmc.org/jira/browse/SPIGOT-4295 ) but its not likely to get fixed any time soon according to md_5's comments.

I would recommend the OP look at using the CommandHook plugin as it seems to add all the original functionality: 
https://www.spigotmc.org/resources/commandhook.61415/

**Comment by Thatsmusic99** [comment]
OP hasn't responded for 2 months and I'm sure this is a suitable solution. Closing now.
