### ISSUE TITLE
[BUG] Strange error on /hpc, no menu shown (since May update)

### ISSUE THREAD

**Issue by LoneDev6** [Thatsmusic99/HeadsPlus#23]
### Description of the bug
/hpc not showing up

### To Reproduce
1. /hpc
2. ???

### Have you been able to reproduce the bug more than once?
yes, everytime

### Expected behavior
No error

Error: https://pastebin.com/TcVRbVPL

### Required information
- Server version: This server is running Paper version git-Paper-371 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- HeadsPlus version: 6.10.10
- Whether or not the plugin uses MySQL: No
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes

**Comment by Thatsmusic99** [comment]
I’m assuming from the error that there’s something wrong with your inventory configuration; if you’re using the default settings, have you tried resetting inventories.yml? Of course I will be sure to investigate further.

**Comment by LoneDev6** [comment]
Thanks a lot for your time!
No I didn't try, do you think it would work?
Also, sorry for the dumb question, is there a reload command?

Thanks a lot for your hard work

Here is my file: https://pastebin.com/AT1vGjt6

**Comment by Thatsmusic99** [comment]
Seeing as the file uses the old challenge menu format for icons, yes, there may be a chance that it’ll fix it. I don’t recall removing it entirely, but it’s definitely depreciated. 

The reload command for HP is /hp reload, no worries at all about that!

**Comment by LoneDev6** [comment]
Resetting the file worked fine! Thanks a lot
