### ISSUE TITLE
[BUG] InventoryClickEvent exception

### ISSUE THREAD

**Issue by LoneDev6** [Thatsmusic99/HeadsPlus#25]
### Description of the bug
Error spammed in console multiple times

### To Reproduce
unknown

### Have you been able to reproduce the bug more than once?
Nope

### Required information
    Server version: This server is running Paper version git-Paper-371 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
    HeadsPlus version: 6.10.10
    Whether or not the plugin uses MySQL: No
    Server type (e.g Spigot, Paper): Paper
    Uses Vault: Yes

## Additional information
https://pastebin.com/NrLqN30k

**Comment by Thatsmusic99** [comment]
Honestly, I don't think I have enough information to work from here, especially since I can't even tell _when_ it's occuring or how to reproduce it. I'll be looking to see if I can make some debugging improvements in a future release so that this is easy to figure out.

**Comment by Chew** [comment]
I have this issue as well with my projects. Some people say it's because a GUI doesn't have a title or something? I forgot the exact reason but I don't think it's the plugin's fault.

**Comment by Thatsmusic99** [comment]
As of currently, I doubt it's the above. The error is thrown on the following line:
```        } else if (currentPage > inventory.contents.getTotalPages()) {```
And since it's a NullPointerException, I'm guessing the contents are null? Or is it the inventory?

In v6.11-SNAPSHOT-1 I'll see if this bug can be diagnosed through some of the new debug mechanics I'm using (which I've confirmed work, just need to port them over to all the other events).

**Comment by Thatsmusic99** [comment]
Can I ask if the error has occured on more than one occasion @LoneDev6? Or was this more of a one-off situation?

**Comment by Chew** [comment]
Finally found the error I was having, not all inventories have a holder so every time someone interacted with one that didn't it would raise that. I checked to make sure the inventory holder isn't null and it works fine now.

**Comment by Thatsmusic99** [comment]
Ah, thought this was in relation to the original error for a second and was going to ask how you managed to reproduce it. At this rate, I may just have to include a check which makes sure the BaseInventory isn't null. Although, I'll have to do that when I have a laptop that can handle programming decently.

**Comment by Chew** [comment]
Yeah, IntelliJ even warned me that "x might return NullPointerException" and guess what happens when it does?

**Comment by LoneDev6** [comment]
Sorry for the late answer, I was out of town.
Happy you fixed the issue :D

**Comment by Thatsmusic99** [comment]
Ah, I don't recall fixing it unless you count this commit: https://github.com/Thatsmusic99/HeadsPlus/commit/86327728a3e8ed8ebb806db8b2577620681bd07f

**Comment by Chew** [comment]
Here's my fix
https://github.com/ChewMC/TransmuteIt/compare/45a184a92c811680ed6f4362bf82067d996197bc...5ae60ea6d5c28d4218aae6efc729ab30b623b854

**Comment by Thatsmusic99** [comment]
I think it was a slightly different issue that we were having there since the `inventory` in the code was actually a `BaseInventory`, an internal class in HP itself
