### ISSUE TITLE
Remove Redundant Warning: Skull textures no longer an issue with latest Paper

### ISSUE THREAD

**Issue by MagicGonads** [Thatsmusic99/HeadsPlus#26]
The issue https://github.com/PaperMC/Paper/issues/3667 is now closed and the bug is fixed
The warning and disabled commands are no longer necessary (as far as I can see)

Warning issued by HeadsPlus v6.10.10
```
>....     [22:57:00 WARN: [HeadsPlus] WARNING: Due to Paper's current state (1.16.1), HeadsPlus does not function correctly.]
>....     [22:57:00 WARN: [HeadsPlus] It will not be disabled, however /head and /myhead have been disabled due to critical bugs.]
>....     [22:57:00 WARN: [HeadsPlus] For more information, please refer to https://github.com/PaperMC/Paper/issues/3667]
>....     [22:57:00 WARN: [HeadsPlus] Custom head textures will not work either, and nor will they work for other plugins.]
>....     [22:57:00 WARN: [HeadsPlus] Once the issue is fixed, this warning will be removed.]
```

**Comment by Thatsmusic99** [comment]
Have been aware of this for a while now and it will be removed in the near future once I finish v6.11.

**Comment by Thatsmusic99** [comment]
Actually, I've held off v6.11 for a bit too long now with other projects interfering. I'll sort this out now and release it on Spigot, then sort out that release for next time.
