### ISSUE TITLE
Sheep head not displaying

### ISSUE THREAD

**Issue by mistek131995** [Thatsmusic99/HeadsPlus#26]
**Short summary of issue:** Sheep head not displaying in sell menu

**Server version:** 1.13.2

**HeadsPlus version:** 6.0.1

![2019-03-17_00 37 41](https://user-images.githubusercontent.com/14914380/54481996-6ffc5400-484d-11e9-879b-14c9f79a6621.png)

**Comment by Thatsmusic99** [comment]
Will try and reproduce on v6.0.2-SNAPSHOT-1.

**Comment by Thatsmusic99** [comment]
Reproduced with another issue.

**Comment by Thatsmusic99** [comment]
Fixed in latest snapshot: https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v6.0.2-SNAPSHOT-2

**Comment by Thatsmusic99** [comment]
Closing now as there has been no further comment on this from OP and no reports on it from other users.
