### ISSUE TITLE
[BUG] Extreme lag on GUI click

### ISSUE THREAD

**Issue by LoneDev6** [Thatsmusic99/HeadsPlus#29]
### Description of the bug
Extreme lag on GUI click

### To Reproduce
1. update to 1.16.2
2. open the hpc menu
3. click
4. you see server freezes

### Have you been able to reproduce the bug more than once?
yes, everytime

### Expected behavior
no lag

### Required information
- Server version: This server is running CraftBukkit version git-Spigot-379750e-fe4efd1 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
- HeadsPlus version: 6.11-SNAPSHOT-2
- Whether or not the plugin uses MySQL: NO
- Server type (e.g Spigot, Paper): Spigot
- Uses Vault: YES

## Additional information
https://spark.lucko.me/#reT47mu5JU

![image](https://user-images.githubusercontent.com/27242001/90900143-43952180-e3c9-11ea-9332-8999b9949b9e.png)

**Comment by cloakfox** [comment]
Same issue here.

![Capture](https://user-images.githubusercontent.com/3696645/93236433-1e54c280-f77f-11ea-86dd-384be7daa925.PNG)

HeadsPlus MySQL data storage causes memory leaks btw, so we dont use it anymore.

**Comment by Thatsmusic99** [comment]
> 
> 
> Same issue here.
> 
> ![Capture](https://user-images.githubusercontent.com/3696645/93236433-1e54c280-f77f-11ea-86dd-384be7daa925.PNG)
> 
> HeadsPlus MySQL data storage causes memory leaks btw, so we dont use it anymore.

Please make a new issue with more details, I don't know what plugin version is being used and MySQL is NOT being used in this issue.

**Comment by cloakfox** [comment]
> > Same issue here.
> > ![Capture](https://user-images.githubusercontent.com/3696645/93236433-1e54c280-f77f-11ea-86dd-384be7daa925.PNG)
> > HeadsPlus MySQL data storage causes memory leaks btw, so we dont use it anymore.
> 
> Please make a new issue with more details, I don't know what plugin version is being used and MySQL is NOT being used in this issue.

You are really fast, I was about to reply that I was still on 6.10.11, I just tried updating live but this plugin doesnt like plugman at all, will report tomorrow how it's going.

**Comment by Thatsmusic99** [comment]
> 
> 
> > > Same issue here.
> > > ![Capture](https://user-images.githubusercontent.com/3696645/93236433-1e54c280-f77f-11ea-86dd-384be7daa925.PNG)
> > > HeadsPlus MySQL data storage causes memory leaks btw, so we dont use it anymore.
> > 
> > 
> > Please make a new issue with more details, I don't know what plugin version is being used and MySQL is NOT being used in this issue.
> 
> You are really fast, I was about to reply that I was still on 6.10.11, I just tried updating live but this plugin doesnt like plugman at all, will report tomorrow on how it's going.

Discord notifications are indeed superior when it comes to notifying me about stuff!

And yes, I would check using a newer version of the plugin, as I did mention in an earlier comment that I made a few improvements to the plugin (SNAPSHOT-3 specifically), and I thought I made MySQL async (should've been already) but I may be wrong.

**Comment by Thatsmusic99** [comment]
Since I haven't received further notice about whether this bug is sorted or not I will start considering this issue stale but will close it once v6.11 releases. If this issue persists in later versions though, please bump the issue or re-open it if I've closed it.

**Comment by LoneDev6** [comment]
I didn't test the new releases but:
>  why are you sorting the scores each time a player is opening the GUI?


This is a bad practice, just save them as sorted instead of sorting them each time a player opens the GUI

**Comment by Thatsmusic99** [comment]
It doesn't even need sorting when the player opens a GUI for themselves, I even removed this entirely in the new releases; this was a flaw in the existing API, as I mentioned further up:

> I don't know either, I changed that in SNAPSHOT-3 lol (available on Spigot now)

**Comment by LoneDev6** [comment]
Very nice! Thanks for your hard work 👍
Have a nice day
