### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType

### ISSUE THREAD

**Issue by OverlordFreddo** [Thatsmusic99/HeadsPlus#30]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
State here when you have checked the following points above.
Yes, 6.11-SNAPSHOT-3
After serveral searches of tte issues both open and closed, for `No enum constant org.bukkit.entity.EntityType` I can reasonably conclude there's nothing like this.

### Description of the bug
I was asleep at the time the console spam happened but through asking I found that a (brand new) player put a zombie head on their head.

### To Reproduce

1. Stick a zombie head, on your head.
2. ???
3. Profit?

### Have you been able to reproduce the bug more than once?
[Working on it.... will update when I/one of my admins can reproduce it]
Maybe getting my hands on the actual head would be of assistance in some way?

### Expected behavior

Someone putting a mobhead on their head and the server knowing what type of mobhead it is...

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

[08.24.2020 16_24_46-REPORT-1.json.txt](https://github.com/Thatsmusic99/HeadsPlus/files/5119176/08.24.2020.16_24_46-REPORT-1.json.txt)

### Required information
- Server version: `Paper 1.16.1 #138`
- HeadsPlus version: `6.11-SNAPSHOT-3`
- Whether or not the plugin uses MySQL: Nope
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes (`1.7.3-b131`)
- Any other pieces of information that may be required.

## Additional information
Add any other information/notes you'd like to add at the bottom
I see that I have more than one report for exactly the same issue and that the 'special messages' are random and humorous. Made my day ^.^

**Comment by Thatsmusic99** [comment]
I can see a potential cause of this, although I don't actually see how it can be caused considering how far the code actually got; it's meant to simply stop if the slot isn't the one it wants (the one it wants is the crafting output, not the head slot).

If you do want to attempt to reproduce, please try using a zombie head taken from the creative inventory and one taken from /hp conjure ZOMBIE.

And thank you, it's the most effort I've ever put in this plugin

**Comment by OverlordFreddo** [comment]
I have attempted to reproduce by 
> using a zombie head taken from the creative inventory and one taken from /hp conjure ZOMBIE

However, nothing revealed itself.

I also got the suspected person online to check out their heads.  We both put them on our heads (and they put one in their offhand too). Unable to reproduce.

Could it be an old head from a previous HeadsPlus version?  Our server was last reset when 1.16 was released which would give you a timeframe.

I did notice though, any heads that are placed have their lore stripped and becomes either a normal zombie head or a player head of a different name.

The console error/dump happened again.  I can't be sure if it's exactly the same error so I'll attach that too.

[08.24.2020 18_22_32-REPORT-0.json.txt](https://github.com/Thatsmusic99/HeadsPlus/files/5119606/08.24.2020.18_22_32-REPORT-0.json.txt)

**Comment by OverlordFreddo** [comment]
Error happens using `SNAPSHOT-4` given via Discord.  I believe it's the same error happening over and over but I'll attach the debug report anyway.
[08.25.2020 04_34_26-REPORT-0.json.txt](https://github.com/Thatsmusic99/HeadsPlus/files/5121552/08.25.2020.04_34_26-REPORT-0.json.txt)

**Comment by OverlordFreddo** [comment]
Debugging again with `SNAPSHOT-4`, which gives different outputs in console than the dump files.

Console output:
![image](https://user-images.githubusercontent.com/7680423/91202739-237f9e00-e6fa-11ea-9325-a5a733803718.png)

Debug dump:
[08.25.2020 14_05_41-REPORT-0.json.txt](https://github.com/Thatsmusic99/HeadsPlus/files/5125152/08.25.2020.14_05_41-REPORT-0.json.txt)

**Comment by Thatsmusic99** [comment]
whoops, forgot to remove the debug code

**Comment by Thatsmusic99** [comment]
Oh dear, I managed to reproduce it with the information provided but found out it was caused whenever someone crafted a non-HeadsPlus item, which is more than bad. Currently, HP's crafting mechanics are very messy, since most of it was written when I was starting out as a programmer. Adding the extra check for WorldGuard clearly broke the final straw for the plugin. 

If you want to avoid this bug, you can temporarily disable the crafting feature (just craft-heads), but I should get this sorted relatively quickly otherwise.

**Comment by OverlordFreddo** [comment]
I appreciate your swift troubleshooting and I'll apply the workaround for the near future.  Thanks again!
