### ISSUE TITLE
TOS/Licensing issues

### ISSUE THREAD

**Issue by leviem1** [Thatsmusic99/HeadsPlus#31]
You state that you're under the MIT license but have the GPL-3.0 license in the project repo. ~~If you *are* migrating away from the MIT license, you will need to prove written consent from any author whose code exists in the project from when the project was under the MIT license (Jul 11, 2019-Jul 11, 2020). If you're not, then you can revert back to MIT as you were the only contributor since the license file was changed.~~

~~[More Information](https://opensource.stackexchange.com/a/2032)~~

EDIT: Sorry, MIT can go to GPL without theses steps since it's GPL compatible, but not the other way without permission.

Additionally, your TOS violates **both** the MIT and GPL-3.0 licenses which allow modification and distribution. You cannot restrict the redistribution of your project nor can you restrict the distribution of modified versions of the project.

**Disclaimer:** I'm not a lawyer, so you should speak to a legal consultant.

**Comment by leviem1** [comment]
Totally willing to help you resolve this btw! Just wanted to make the issue clear. Hope it didn't come across harshly!

**Comment by Thatsmusic99** [comment]
Thanks for the heads up (no pun intended); I originally moved away from MIT as I was made aware by another plugin developer that legally, all plugins should be licensed under GPL as Bukkit was under the same license. In response to this, I did migrate whilst possible.

I'm more than willing to resolve this so give me a moment to go over your concerns and I'll respond again.

**Comment by Thatsmusic99** [comment]
Ah, the TOS I included. My main reasoning for this was I wanted people to avoid reposting my work without permission but it's a half finished document, and the GPL/code of conduct should be enough.

I'll remove it as soon as I get the chance; let me know if there's anything else that is required to resolve this.

**Comment by leviem1** [comment]
Sounds good! I think the TOS is great as long as you're careful not to contradict the GPL. Out of curiosity, was the choice to include the TOS made to protect potential profits or something? If so, I'd highly recommend offering a paid version of the plugin that comes with support (maybe guaranteed within 48 hours) or a "support subscription". Try selling *services* rather than products since services can't be copied/pasted. 

Good call on switching to GPL with that "linking" legal caveat, though there's an interesting conversation about it [here] (https://bukkit.org/threads/what-license-is-the-bukkit-project-under.154/) essentially saying they won't press charges. Better safe than sorry nonetheless! I'll likely be reviewing my licenses shortly as I hadn't made that connection either. 😄

**Comment by Thatsmusic99** [comment]
I believe it was a move I chose to make because I wanted to rule out what I consider acceptable use of the plugin (so not using it to bully others as an example); however, I don't plan on charging anything for HeadsPlus because it is my first plugin and I want to keep it free for everyone to use, nor do I want to profit off plugins anyways.

Yes, I do want to stay safe rather than become sorry in the future when it comes to anything legal. I've removed the TOS in question so hopefully, this should solve the conflict it created. Thank you for pointing me in the right direction regarding all of this!

**Comment by leviem1** [comment]
No problem! And thank you for being responsive and satisfying my curiosity.

The GPL defers all liabilities to the users anyways, so it protects you quite a bit from that. Unfortunately, the GPL is too restrictive for your good intentions.

For any other projects of yours, I'd recommend the [Apache 2.0](https://exygy.com/blog/which-license-should-i-use-mit-vs-apache-vs-gpl/). It's basically the MIT with extra legal precautions against "Patent Trolls".
