### ISSUE TITLE
Blaze head not visible.

### ISSUE THREAD

**Issue by Diablolend** [Thatsmusic99/HeadsPlus#33]
![2020-11-12_00 09 22](https://user-images.githubusercontent.com/11898488/98853853-91c33980-247b-11eb-8935-7ed82dbcc918.png)

**Comment by Thatsmusic99** [comment]
If you're on a modded client then please try it with a Vanilla client.

**Comment by Diablolend** [comment]
@Thatsmusic99. Well. On vanilla that work fine, but why one head become with white color and the rest work properly? 🤔

**Comment by Thatsmusic99** [comment]
For that part, I don't know. HeadsPlus operates purely server-side so I don't believe it's a problem on our end; you may need to report the problem to the client's developers. If they need extra information, then they're free to ask me.
