### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oranges13** [Thatsmusic99/HeadsPlus#34]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS? Have you checked to see if others have submitted the same bug report? 
- [x] Yes, I have checked existing bug reports
- [x] Yes, I am using the latest version (6.11.1)

### Description of the bug
This error message appears in the server log:
```
[11:14:49 ERROR]: There is a configuration error in the plugin configuration files! Details below:
[11:14:49 ERROR]: while parsing a block mapping
 in 'string', line 76, column 3:
      locale:
      ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 158, column 5:
        not-enough-heads: '{header} 你头颅不够!'
        ^

[11:14:49 ERROR]: We have renamed the faulty configuration to zh_cn-errored.yml for you to inspect.
[11:14:49 ERROR]: When you believe you have fixed the problems, change the file name back to zh_cn.yml and reload the configuration.
[11:14:49 ERROR]: If you are unsure, please contact the developer (Thatsmusic99).

```
### To Reproduce
1. Install latest version in plugin folder
2. Start server
3. Observe error

### Have you been able to reproduce the bug more than once?
Yes

### Expected behavior
No error messages in the server log

### Has a debug report been generated? 
If you have a debug report, go to plugin/HeadsPlus/debug, copy your report onto pastebin or hastebin, and paste it here, but also skip to the bottom question (additional information). If you don't, fill in the information below.

### Required information
- Server version: 1.15.2
- HeadsPlus version: 6.11.1
- Whether or not the plugin uses MySQL: no
- Server type (e.g Spigot, Paper): Paper
- Uses Vault: Yes
- Any other pieces of information that may be required.

## Additional information
Add any other information/notes you'd like to add at the bottom

The plugin renamed this configuration file that it says is the culprit https://paste.ubuntu.com/p/GZHjBtW6TJ/

**Comment by Thatsmusic99** [comment]
Can you try resetting the locale file? This should've been fixed in one of the previous releases.

**Comment by oranges13** [comment]
We noticed this while upgrading from 6.11-beta-1 to 6.11.1 on multiple servers. On subsequent restarts it seems like the error is gone.
