### ISSUE TITLE
[BUG] Unquoted Variables

### ISSUE THREAD

**Issue by bundabrg** [Thatsmusic99/HeadsPlus#35]
### Description of the bug
A typical head blockstate could be as follows:
```
minecraft:player_head[rotation=9]{Owner:{Id:"0bbd8cd5-ef7e-3468-9a52-15d74185212a",Properties:{textures:[{Value:"e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODM5YWY0NzdlYjYyNzgxNWY3MjNhNTY2MjU1NmVjOWRmY2JhYjVkNDk0ZDMzOGJkMjE0MjMyZjIzZTQ0NiJ9fX0="}]},Name:"HPXHead"}}
```

The decoded value is:
```
{textures:{SKIN:{url:"http://textures.minecraft.net/texture/839af477eb627815f723a5662556ec9dfcbab5d494d338bd214232f23e446"}}}
```

This has missing quotes on the variables names which can cause issues (translating a head to bedrock using Geyser gets stuck on this issue). 
I recommend making sure all variables are properly quoted. Here is an older head on my server that works fine:
```
minecraft:player_head[rotation=7]{Owner:{Id:"913e13b0-29b5-3dac-b14e-89b147bab990",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2U0MWM2MDU3MmM1MzNlOTNjYTQyMTIyODkyOWU1NGQ2Yzg1NjUyOTQ1OTI0OWMyNWMzMmJhMzNhMWIxNTE3In19fQ"}]},Name:"HPXHead"}}
```

which decodes to

```
{
  "textures": {
    "SKIN": {
      "url": "http://textures.minecraft.net/texture/3e41c60572c533e93ca421228929e54d6c856529459249c25c32ba33a1b1517"
    }
  }
}
```

Note. I work around the issue by allowing unquoted but its better to fix at the source.

### Required information
- Server version: Spigot-v1.16.4
- HeadsPlus version: v6.11.1
- Whether or not the plugin uses MySQL: no
- Server type (e.g Spigot, Paper):: spigot
- Uses Vault: yes

Related Issue: https://github.com/bundabrg/Geyser/issues/10

**Comment by Thatsmusic99** [comment]
I didn't even realise skulls were meant to work in Bedrock, that's impressive to see. I've pushed a fix for it on my end.

I can't test it right now as I'm running around with schoolwork a bit, but you can try the patched jar [here](https://cdn.discordapp.com/attachments/269172690957369355/781461703522648084/HeadsPlus-v6.11.2-SNAPSHOT-1.jar).

Let me know if this fixes it!

**Comment by DoctorMacc** [comment]
Our workaround uses player entities for skulls, so no, they weren't "meant" to work. :P

Your fix doesn't appear to work, but don't worry too much about it, as our skull support has not yet been merged into master and I've applied Bundabrg's fix that fixes the problem on our end (which we need to do anyway, since if a Java client supports it, we should too).

**Comment by Thatsmusic99** [comment]
Still a super impressive way to implement them!

I probably should've mentioned that the fix doesn't apply itself to already-generated skulls but rather new ones, but if that didn't work either, that's fine. Either way, you've got a workaround which should address the problem. 

I'll close the issue now as the actual problem within the plugin has been addressed (this being the unquoted variables), but if there's anything else I need to do, feel free to re-open or create another issue. Thank you for your time!

**Comment by bundabrg** [comment]
Thanks and appreciate the quick fix. I'll test it decodes ok. The skulls are entities with a geometry of just the skull and works pretty well (apart from the items being just Steve heads when held). My players have bukkit loads of heads on the server and it works well.
