### ISSUE TITLE
[QUESTION] {killer} tag not working

### ISSUE THREAD

**Issue by DiaxManPl** [Thatsmusic99/HeadsPlus#37]
I have a lore configuration (in `mobs.yaml`) like this:
![image](https://user-images.githubusercontent.com/63294962/108467840-2365f280-7286-11eb-8669-17bbd1650ea2.png)
but when I kill a player, the `Killer` section is `Killer: {killer}`, not `Killer: DiaxManPl` (DiaxManPl is my nickname in mc).
What did I do wrong?

**Comment by Thatsmusic99** [comment]
No such placeholder exists right now. I believe it's in the pipeline right now though.

**Comment by Thatsmusic99** [comment]
Then they are not using HeadsPlus.

![](https://i.gyazo.com/7d95186788041166db09734132582190.png)

**Comment by DiaxManPl** [comment]
Ok sorry
