### ISSUE TITLE
Left arm head selling bug!

### ISSUE THREAD

**Issue by favorit5503** [Thatsmusic99/HeadsPlus#4]
### Short summary of issue
Hi. I noticed a problem if you hold the head in you left arm and you sell it you recieve the money but the head is still there you can repeat is unlimited times.
### Server version
1.12.2 Paper
### HeadsPlus version
4.8
### Detailed description (how you found it, what you were doing at the time)
Hi. I noticed a problem if you hold the head in you left arm and you sell it you recieve the money but the head is still there you can repeat is unlimited times.
### Expected behaviour
[Left] Arm - Sell a head and then the head is removed
### Actual behaviour
[Left] Arm - Sell a head and then the head is not removed can sell the same head again
### Steps to reproduce
Hold a head in you left arm and try to sell it.
### Any last notes?

**Comment by Thatsmusic99** [comment]
Reproduced in Paper Spigot 1.12.2 - will attempt to fix by tonight.

**Comment by Thatsmusic99** [comment]
Tested and fixed in the latest version, 4.8.1.
