### ISSUE TITLE
Incorrect Display Name

### ISSUE THREAD

**Issue by chrissch33** [Thatsmusic99/HeadsPlus#5]
### Short summary of issue
The head's displayname is displayed as "%d's head"

### Server version
Spigot 1.12.2_6_20

### HeadsPlus version
4.8.2

### Detailed description (how you found it, what you were doing at the time)
I used `/myhead`. I reproduced this issue multiple times: right after installing it as well as moments later after configuring permissions and configs.
<http://prntscr.com/k4spi5>

### Expected behavior
I'm guessing it's supposed to have my name instead of `%d`

### Actual behaviour
There's a `%d` instead of my name.

### Steps to reproduce
1. Install plugin
2. `/myhead`

**Comment by Thatsmusic99** [comment]
The tag should be %player% instead, and it should've updated, but my best guess was that didn't happen. Just change it and it should work.
