### ISSUE TITLE
Doesn't Allow for Usernames that are 16 Characters Long or 3 Characters Long

### ISSUE THREAD

**Issue by chrissch33** [Thatsmusic99/HeadsPlus#6]
### Short summary of issue
Using `/head Hextaine SchoolbagSealion` and `/head Hextaine GGG` reports an error that the name I provided was too long or too short.

### Server version
Spigot 1.12.2_6_20

### HeadsPlus version
4.8.2

### Detailed description (how you found it, what you were doing at the time)
Any use of the command `/head MyUserName SchoolbagSealion` will report an error saying, "IGN is too long to be valid! Please use an IGN between 3 and 16 characters." when in fact usernames are allowed to be both 3 characters long and 16 characters long.
16 Character Reference: <https://namemc.com/profile/SchoolbagSealion.1>
3 Character Reference: <https://namemc.com/profile/GGG.2>

### Expected behaviour
I expect their head for all of this.

### Actual behaviour
Error: "IGN is too long to be valid! Please use an IGN between 3 and 16 characters."

### Steps to reproduce
1. Install
2. `/head <My Username> SchoolbagSealion`
OR
2. `/head <My Username> GGG`

### Any last notes?
Both the username SchoolbagSealion _AND_ GGG report being too long even though 'GGG' is supposed to be recognized as too short according to your current restrictions of usernames. Basically, 'GGG' is reported as being too long as well. Not that I really care, just a small thing: food for thought, if you will.

**Comment by Thatsmusic99** [comment]
To be fixed in the next version.

And food for thought? As in?
