### ISSUE TITLE
[5.2.2] Crafting only gives a skeleton_skull every time

### ISSUE THREAD

**Issue by steve4744** [Thatsmusic99/HeadsPlus#9]
### Short summary of issue
Hi, 
5.2.2 hasn't really fixed the crafting issue on 1.13.1 mentioned in #8.
Crafting with skeleton_skull/item still does nothing.
Crafting with player_head/item gives you a skeleton skull with every item

### Server version
1.13.1
### HeadsPlus version
5.2.2
### Detailed description (how you found it, what you were doing at the time)
![2018-10-09_20 32 10](https://user-images.githubusercontent.com/6975392/46694331-6159a300-cc04-11e8-971e-87914f066e59.png)

### Expected behaviour
Craft a head with skeleton_skull and item.
### Actual behaviour
Crafting with skull/item does nothing.
Crafting with player_head/item gives you a skeleton skull
### Steps to reproduce
See photo
### Any last notes?
Apart from enabling crafting in the config, I've not changed any configs, just downloaded the jar, and started afresh.

**Comment by Thatsmusic99** [comment]
I seriously need to learn to not doze off whilst writing code. Damnit.

**Comment by Thatsmusic99** [comment]
Should be fixed in the latest version.
